# Generated by Django 4.0.4 on 2022-05-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_entry_key_days_entry_positive_percent_entry_rating_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='rating_1',
            field=models.DecimalField(decimal_places=10, max_digits=11),
        ),
        migrations.AlterField(
            model_name='entry',
            name='rating_2',
            field=models.DecimalField(decimal_places=10, max_digits=11),
        ),
        migrations.AlterField(
            model_name='entry',
            name='rating_3',
            field=models.DecimalField(decimal_places=10, max_digits=11),
        ),
        migrations.AlterField(
            model_name='entry',
            name='rating_4',
            field=models.DecimalField(decimal_places=10, max_digits=11),
        ),
        migrations.AlterField(
            model_name='entry',
            name='rating_5',
            field=models.DecimalField(decimal_places=10, max_digits=11),
        ),
    ]
