# Generated by Django 4.0.4 on 2022-05-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0007_alter_entry_rating_1_alter_entry_rating_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
