# Generated by Django 4.0.4 on 2022-05-11 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0016_entry_user_retention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='user_retention',
        ),
    ]
