# Generated by Django 4.0.4 on 2022-05-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0017_remove_entry_user_retention'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='rule',
            field=models.CharField(choices=[('MAJ', 'Majorité'), ('PROP', 'Proportionnelle')], default='MAJ', max_length=5, verbose_name='mode de scrutin'),
        ),
    ]
